version: '3'

services:
  app:
    image: 'auction-service:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8082:8081
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auction-service
      - SPRING_DATASOURCE_USERNAME=dbu_postgres
      - SPRING_DATASOURCE_PASSWORD=VxQ7ooGvU84P
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbu_postgres
      - POSTGRES_PASSWORD=VxQ7ooGvU84P
      - POSTGRES_DB=auction-service
